project_id = "lusbaxesfvicoibnvjcr"
[functions.escrow-actions]
enabled = true
verify_jwt = true
import_map = "./functions/escrow-actions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/escrow-actions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/escrow-actions/*.html" ]

[functions.user-profiles]
enabled = true
verify_jwt = true
import_map = "./functions/user-profiles/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/user-profiles/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/user-profiles/*.html" ]
